### ISSUE TITLE
Get rid of babel-polyfill requirement

### ISSUE THREAD

**Issue by callaars** [RodrigoEspinosa/lookenv#2]
@RodrigoEspinosa you know I love you. What I don't love though, is the required `babel-polyfill` package after I install it. Since I run this mainly in back-end systems, babel is the last thing I want to install.

**Comment by RodrigoEspinosa** [comment]
💯 agreed. There's no point in using babel for node v8 so I'm going to get rid of that whole thing. Love you too buddy!

**Comment by RodrigoEspinosa** [comment]
`v1.0.0` published just for you, mate 💪

**Comment by callaars** [comment]
Ha, thanks man! I really love this package, use it for everything!
